@extends('layouts.app')
@section('title', 'Tổng quan nhân viên')
@section('content')
<x-page-header eyebrow="Khu vực cá nhân" title="Tổng quan của tôi" description="Theo dõi hồ sơ và tình hình chấm công của bạn."><div class="flex flex-wrap gap-2"><a href="{{ route('employee.profile.edit') }}" class="app-button-primary">Cập nhật hồ sơ</a><a href="{{ route('employee.attendances.index') }}" class="app-button-secondary">Lịch sử chấm công</a><a href="{{ route('employee.leave-requests.create') }}" class="app-button-secondary">Gửi đơn xin nghỉ</a></div></x-page-header>
@if($employee)
<div class="app-panel mb-6 flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:p-6">
    @if($employee->avatar_path)<img src="{{ $employee->user->avatar_url }}" alt="Ảnh đại diện {{ $employee->user->name }}" class="h-20 w-20 rounded-2xl object-cover shadow-sm">@else<span class="flex h-20 w-20 items-center justify-center rounded-2xl bg-orange-100 text-2xl font-bold text-orange-700">{{ strtoupper(substr($employee->user->name, 0, 1)) }}</span>@endif
    <div class="min-w-0 flex-1"><h2 class="truncate text-xl font-bold text-[var(--app-text)]">{{ $employee->user->name }}</h2><div class="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-sm text-[var(--app-muted)]"><span>Mã nhân viên: <strong class="text-[var(--app-text)]">{{ $employee->employee_code }}</strong></span><span>Phòng ban: <strong class="text-[var(--app-text)]">{{ $employee->department?->name ?? '—' }}</strong></span><span>Chức vụ: <strong class="text-[var(--app-text)]">{{ $employee->position ?: '—' }}</strong></span></div></div>
</div>
@php($cards = [['Có mặt', (int) ($summary?->present ?? 0), 'text-emerald-600'], ['Đi muộn', (int) ($summary?->late ?? 0), 'text-amber-600'], ['Vắng', (int) ($summary?->absent ?? 0), 'text-red-600'], ['Nghỉ', (int) ($summary?->leave_total ?? 0), 'text-violet-600'], ['Tổng giờ ghi nhận', $workedHours, 'text-sky-600']])
<div class="grid gap-4 sm:grid-cols-2 md:grid-cols-3">@foreach($cards as $card)<div class="app-panel min-h-28 p-5"><p class="text-sm font-medium text-[var(--app-muted)]">{{ $card[0] }}</p><p class="mt-3 text-3xl font-bold {{ $card[2] }}">{{ $card[1] }}</p><p class="mt-1 text-xs text-[var(--app-muted)]">Tháng {{ $currentMonth }}</p></div>@endforeach</div>
<div class="dashboard-two-column mt-6 grid items-stretch gap-6">
    <div class="app-panel min-w-0 p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div><h2 class="app-heading">Chấm công gần đây</h2><p class="app-subtitle">Các bản ghi trong tháng {{ $currentMonth }}</p></div><a href="{{ route('employee.attendances.index') }}" class="shrink-0 text-sm font-semibold text-orange-600">Xem tất cả</a></div><div class="mt-4 overflow-x-auto"><table class="app-table"><thead><tr><th>Ngày</th><th>Check-in</th><th>Check-out</th><th>Trạng thái</th></tr></thead><tbody>@forelse($recentAttendance as $attendance)<tr><td>{{ $attendance->work_date?->format('d/m/Y') }}</td><td>{{ $attendance->check_in ?: '—' }}</td><td>{{ $attendance->check_out ?: '—' }}</td><td><x-status-badge :status="$attendance->status" /></td></tr>@empty<tr><td colspan="4" class="py-10 text-center text-[var(--app-muted)]">Chưa có dữ liệu chấm công.</td></tr>@endforelse</tbody></table></div></div>
    <div class="app-panel p-5 sm:p-6"><h2 class="app-heading">Chỉ số chuyên cần</h2><p class="app-subtitle">Tính từ dữ liệu chấm công khách quan</p><div class="mt-5 space-y-4"><div><div class="flex justify-between text-sm"><span class="text-[var(--app-muted)]">Tỷ lệ có mặt</span><strong class="text-[var(--app-text)]">{{ $attendanceRate }}%</strong></div><div class="mt-2 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-emerald-500" style="width: {{ min(100, $attendanceRate) }}%"></div></div></div><div><div class="flex justify-between text-sm"><span class="text-[var(--app-muted)]">Tỷ lệ đúng giờ</span><strong class="text-[var(--app-text)]">{{ $punctualityRate }}%</strong></div><div class="mt-2 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-sky-500" style="width: {{ min(100, $punctualityRate) }}%"></div></div></div><p class="text-xs text-[var(--app-muted)]">Không có dữ liệu sẽ hiển thị 0%.</p></div></div>
</div>
@else
<div class="app-panel p-6"><x-empty-state title="Chưa có hồ sơ nhân viên" description="Tài khoản chưa được cấu hình hồ sơ. Vui lòng liên hệ Admin/HR." /></div>
@endif
@endsection
