@extends('layouts.app')
@section('title', 'Quản lý tài khoản')
@section('content')
<x-page-header eyebrow="Admin / Tài khoản" title="Quản lý tài khoản" description="Tạo và quản lý quyền truy cập của HR và Employee."><a href="{{ route('admin.users.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">+ Tạo tài khoản</a></x-page-header>
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    <form method="GET" action="{{ route('admin.users.index') }}" class="mb-6 grid gap-3 md:grid-cols-[1fr_auto_auto_auto]"><label class="sr-only" for="user-search">Tìm user</label><input id="user-search" name="search" value="{{ request('search') }}" type="search" placeholder="Tìm theo tên hoặc email..." class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><select name="role" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Tất cả vai trò</option><option value="admin" @selected(request('role') === 'admin')>Admin</option><option value="hr" @selected(request('role') === 'hr')>HR</option><option value="employee" @selected(request('role') === 'employee')>Employee</option></select><select name="account_status" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Tất cả trạng thái</option><option value="active" @selected(request('account_status') === 'active')>Đang hoạt động</option><option value="locked" @selected(request('account_status') === 'locked')>Đã khóa</option></select><button class="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Lọc</button></form>
    <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-slate-200 text-xs uppercase text-slate-500"><tr><th class="px-3 py-3">Tên</th><th class="px-3 py-3">Email</th><th class="px-3 py-3">Vai trò</th><th class="px-3 py-3">Trạng thái</th><th class="px-3 py-3 text-right">Thao tác</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($users as $user)<tr><td class="px-3 py-4 font-medium text-slate-900">{{ $user->name }}</td><td class="px-3 py-4 text-slate-600">{{ $user->email }}</td><td class="px-3 py-4"><x-status-badge :status="$user->role" :label="strtoupper($user->role)" /></td><td class="px-3 py-4"><x-status-badge :status="$user->account_status" :label="$user->account_status === 'active' ? 'Đang hoạt động' : 'Đã khóa'" /></td><td class="px-3 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.users.show', $user) }}" class="text-sm font-semibold text-slate-600 hover:text-indigo-700">Xem</a><a href="{{ route('admin.users.edit', $user) }}" class="text-sm font-semibold text-indigo-600 hover:text-indigo-800">Sửa</a>@if ($user->id !== auth()->id())<form method="POST" action="{{ route($user->account_status === 'active' ? 'admin.users.lock' : 'admin.users.unlock', $user) }}">@csrf @method('PATCH')<button onclick="return confirm('{{ $user->account_status === 'active' ? 'Khóa tài khoản này?' : 'Mở khóa tài khoản này?' }}')" class="text-sm font-semibold {{ $user->account_status === 'active' ? 'text-rose-600' : 'text-emerald-600' }}">{{ $user->account_status === 'active' ? 'Khóa' : 'Mở khóa' }}</button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="px-3 py-4"><x-empty-state title="Không tìm thấy tài khoản" description="Thử thay đổi từ khóa hoặc bộ lọc." /></td></tr>@endforelse</tbody></table></div><div class="mt-6">{{ $users->links() }}</div>
</div>
@endsection
