@extends('layouts.app')
@section('title', 'Báo cáo thống kê')
@section('content')<x-page-header eyebrow="HR / Báo cáo" title="Báo cáo và thống kê" description="Lọc, tổng hợp và xuất đúng tập dữ liệu đang xem."><div class="flex flex-wrap gap-2"><a href="{{ route('hr.reports.export', request()->query()) }}" class="app-button-secondary">Xuất CSV</a><a href="{{ route('hr.reports.print', request()->query()) }}" class="app-button-primary">In báo cáo</a></div></x-page-header>
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><form method="GET" class="mb-6 grid gap-3 md:grid-cols-3 lg:grid-cols-6"><input name="month" type="number" min="1" max="12" value="{{ request('month') }}" placeholder="Tháng" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><input name="year" type="number" min="2000" max="2100" value="{{ request('year') }}" placeholder="Năm" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><select name="department_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Phòng ban</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(request('department_id') == $department->id)>{{ $department->name }}</option>@endforeach</select><select name="employee_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Nhân viên</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(request('employee_id') == $employee->id)>{{ $employee->employee_code }} - {{ $employee->user->name }}</option>@endforeach</select><select name="status" class="rounded-lg border px-3 py-2 text-sm"><option value="">Trạng thái</option>@foreach(['present'=>'Có mặt','late'=>'Đi muộn','absent'=>'Vắng','leave'=>'Nghỉ phép'] as $value=>$label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select><select name="employment_status" class="rounded-lg border px-3 py-2 text-sm"><option value="">Trạng thái việc làm</option><option value="active" @selected(request('employment_status') === 'active')>Đang làm</option><option value="inactive" @selected(request('employment_status') === 'inactive')>Đã nghỉ</option></select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Lọc</button><a href="{{ route('hr.reports.index') }}" class="rounded-lg px-4 py-2 text-sm font-semibold text-slate-500">Đặt lại</a></form>
<div class="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">@foreach(['Tổng'=>$totalRecords,'Có mặt'=>$counts['present'] ?? 0,'Đi muộn'=>$counts['late'] ?? 0,'Vắng'=>$counts['absent'] ?? 0,'Nghỉ phép'=>$counts['leave'] ?? 0] as $label=>$value)<div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-1 text-2xl font-bold text-indigo-700">{{ $value }}</p></div>@endforeach</div>
<div class="mb-6 rounded-xl border border-[var(--app-border)] bg-[var(--app-surface)] p-5"><h2 class="app-heading">Tình trạng chấm công đã lọc</h2><div class="relative mt-4 h-64"><canvas id="attendance-status-chart" aria-label="Biểu đồ tình trạng chấm công"></canvas></div></div>
<div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b text-xs uppercase text-slate-500"><tr><th class="px-3 py-3">Ngày</th><th class="px-3 py-3">Nhân viên</th><th class="px-3 py-3">Phòng ban</th><th class="px-3 py-3">Giờ</th><th class="px-3 py-3">Trạng thái</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($attendances as $attendance)<tr><td class="px-3 py-4">{{ $attendance->work_date->format('d/m/Y') }}</td><td class="px-3 py-4">{{ $attendance->employee->employee_code }} - {{ $attendance->employee->user->name }}</td><td class="px-3 py-4">{{ $attendance->employee->department->name }}</td><td class="px-3 py-4">{{ $attendance->check_in ?: '—' }} - {{ $attendance->check_out ?: '—' }}</td><td class="px-3 py-4"><x-status-badge :status="$attendance->status" :label="ucfirst($attendance->status)" /></td></tr>@empty<tr><td colspan="5" class="px-3 py-5"><x-empty-state title="Không có dữ liệu phù hợp" /></td></tr>@endforelse</tbody></table></div><div class="mt-6">{{ $attendances->links() }}</div></div>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded', () => window.renderDashboardCharts({ attendanceStatus: { labels: ['Có mặt', 'Đi muộn', 'Vắng mặt', 'Nghỉ phép'], values: [{{ $counts['present'] ?? 0 }}, {{ $counts['late'] ?? 0 }}, {{ $counts['absent'] ?? 0 }}, {{ $counts['leave'] ?? 0 }}] }, departments: { labels: [], values: [] }, trend: [] }));</script>@endpush
