@extends('layouts.app')
@section('title', 'Cập nhật hồ sơ')
@section('content')
<x-page-header eyebrow="Cá nhân" title="Cập nhật thông tin cá nhân" description="Chỉ được thay đổi các trường cá nhân được cho phép." />
<div class="app-panel p-5 sm:p-6">@if($employee)
<form method="POST" action="{{ route('employee.profile.update') }}" enctype="multipart/form-data" x-data="{ preview: '{{ $employee->user->avatar_url ?? '' }}' }">
    @csrf @method('PUT')
    <div class="mb-6 flex items-center gap-4 border-b border-[var(--app-border)] pb-6"><template x-if="preview"><img :src="preview" alt="Xem trước ảnh đại diện" class="h-20 w-20 rounded-2xl object-cover"></template><template x-if="!preview"><span class="flex h-20 w-20 items-center justify-center rounded-2xl bg-orange-100 text-2xl font-bold text-orange-700">{{ strtoupper(substr($employee->user->name, 0, 1)) }}</span></template><div><p class="font-semibold text-[var(--app-text)]">{{ $employee->user->name }}</p><p class="text-sm text-[var(--app-muted)]">{{ $employee->employee_code }} · {{ $employee->department?->name ?? '—' }}</p></div></div>
    <div class="grid gap-5 md:grid-cols-2"><div><label for="phone" class="app-label">Điện thoại</label><input id="phone" name="phone" value="{{ old('phone', $employee->phone) }}" class="app-input mt-2 w-full">@error('phone')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="date_of_birth" class="app-label">Ngày sinh</label><input id="date_of_birth" name="date_of_birth" type="date" value="{{ old('date_of_birth', $employee->date_of_birth?->format('Y-m-d')) }}" class="app-input mt-2 w-full">@error('date_of_birth')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div class="md:col-span-2"><label for="address" class="app-label">Địa chỉ</label><textarea id="address" name="address" rows="3" class="app-input mt-2 w-full">{{ old('address', $employee->address) }}</textarea>@error('address')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div class="md:col-span-2"><label for="avatar" class="app-label">Ảnh đại diện</label><input id="avatar" name="avatar" type="file" accept="image/jpeg,image/png,image/webp" @change="preview = URL.createObjectURL($event.target.files[0])" class="mt-2 block w-full text-sm text-[var(--app-text)]"><p class="mt-1 text-xs text-[var(--app-muted)]">JPG, PNG hoặc WEBP; tối đa 2 MB.</p>@error('avatar')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div></div>
    <div class="mt-6 flex flex-wrap gap-3"><button type="submit" class="app-button-primary">Lưu thay đổi</button><a href="{{ route('employee.profile.show') }}" class="app-button-secondary">Hủy</a></div>
</form>
@else<x-empty-state title="Chưa có hồ sơ nhân viên" description="Không thể cập nhật khi hồ sơ chưa được cấu hình." />@endif</div>
@endsection
